name: Run test

on: 
    workflow_dispatch:

jobs:
    setup-fpm:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup latest Fortran Package mananger
              uses: fortran-lang/setup-fpm@v6.1.0
              with:
                    fpm-version: 'v0.10.1'
            #- name: Install fpm by python
            #  run: pip install fpm
            
            - name: Run test
              run: fpm test
